export const HTTP_STATUS_CODES = {
  NOT_FOUND: 404,
  CLIENT_ERROR_MIN: 400,
  CLIENT_ERROR_MAX: 499,
  SERVER_ERROR_MIN: 500,
  SERVER_ERROR_MAX: 599,
} as const;

export const TIMING = {
  MS_PER_MINUTE: 60 * 1000,
} as const;
